package AppMath;

import MiMath.MetMath;
import javax.swing.JFrame;

public class Combinacion extends javax.swing.JFrame {
    
    MetMath m=new MetMath(); 
    
    public Combinacion() {
        super("Combinación");
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        lbRespuesta.setVisible(false);
        lbResultado.setVisible(false);
        lbRN.setVisible(false);
        lbRR.setVisible(false);
        lbRC.setVisible(false);
        this.setVisible(true);
        btnBorrar.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbCombinacion = new javax.swing.JLabel();
        lbIzquierda = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbArriba = new javax.swing.JLabel();
        lbAbajo = new javax.swing.JLabel();
        lbN = new javax.swing.JLabel();
        lbR = new javax.swing.JLabel();
        txtN = new javax.swing.JTextField();
        txtR = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        lbResultado = new javax.swing.JLabel();
        lbRN = new javax.swing.JLabel();
        lbRR = new javax.swing.JLabel();
        lbRC = new javax.swing.JLabel();
        lbRespuesta = new javax.swing.JLabel();
        btnBorrar = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 153));

        lbCombinacion.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lbCombinacion.setForeground(new java.awt.Color(0, 51, 51));
        lbCombinacion.setText("Combinación");

        lbIzquierda.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbIzquierda.setText("nCr=");

        jLabel2.setText("----------------------");

        lbArriba.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbArriba.setText("n!");

        lbAbajo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbAbajo.setText("r! ( n - r )!");

        lbN.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lbN.setText("n:");

        lbR.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lbR.setText("r:");

        txtN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNActionPerformed(evt);
            }
        });

        btnCalcular.setBackground(new java.awt.Color(51, 0, 255));
        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        lbResultado.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbResultado.setForeground(new java.awt.Color(0, 153, 51));
        lbResultado.setText("Resultado");

        lbRN.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbRN.setText("jLabel3");

        lbRR.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbRR.setText("jLabel4");

        lbRC.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbRC.setText("jLabel7");

        lbRespuesta.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbRespuesta.setText("jLabel3");

        btnBorrar.setBackground(new java.awt.Color(0, 0, 0));
        btnBorrar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnBorrar.setForeground(new java.awt.Color(255, 255, 255));
        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 15, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lbCombinacion, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbRR))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(btnCalcular)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbRC)
                                .addGap(45, 45, 45))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lbR)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtR))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbN)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtN, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lbRN)
                                .addGap(96, 96, 96))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lbResultado)
                                .addGap(27, 27, 27)))))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbAbajo)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbIzquierda)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(lbArriba)))))
                .addGap(18, 18, 18)
                .addComponent(lbRespuesta)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnBorrar))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbCombinacion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbArriba)
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbRespuesta)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lbIzquierda)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbAbajo)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbN)
                            .addComponent(txtN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbR)
                            .addComponent(txtR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbResultado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbRN)
                            .addComponent(lbRR))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCalcular)
                    .addComponent(lbRC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(btnBorrar))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        lbRN.setText("n: "+txtN.getText());
        lbRR.setText("r: "+txtR.getText());
        
        int n,r;
        n=Integer.parseInt(txtN.getText());
        r=Integer.parseInt(txtR.getText());
        lbRC.setText("C: "+Double.toString(m.Combinacion(n,r)));
        lbIzquierda.setText(n+"C"+r+" = ");
        lbArriba.setText(n+"!");
        lbAbajo.setText(r+"! ("+n+" - "+r+" )! ");
        lbRespuesta.setText("= "+Integer.toString(m.Combinacion(n,r)));
        lbRespuesta.setVisible(true);
        lbResultado.setVisible(true);
        lbRN.setVisible(true);
        lbRR.setVisible(true);
        lbRC.setVisible(true);
        
        btnBorrar.setVisible(true);
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        lbIzquierda.setText("nCr=");
        lbArriba.setText("n!");
        lbAbajo.setText("r! ( n - r )! ");
        lbRespuesta.setVisible(false);
        lbResultado.setVisible(false);
        lbRN.setVisible(false);
        lbRR.setVisible(false);
        lbRC.setVisible(false);
        txtN.setText("");
        txtR.setText("");
        
        btnBorrar.setVisible(false);
    }//GEN-LAST:event_btnBorrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Combinacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Combinacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Combinacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Combinacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Combinacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbAbajo;
    private javax.swing.JLabel lbArriba;
    private javax.swing.JLabel lbCombinacion;
    private javax.swing.JLabel lbIzquierda;
    private javax.swing.JLabel lbN;
    private javax.swing.JLabel lbR;
    private javax.swing.JLabel lbRC;
    private javax.swing.JLabel lbRN;
    private javax.swing.JLabel lbRR;
    private javax.swing.JLabel lbRespuesta;
    private javax.swing.JLabel lbResultado;
    private javax.swing.JTextField txtN;
    private javax.swing.JTextField txtR;
    // End of variables declaration//GEN-END:variables
}
